name: Build Void OS Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Podman
        uses: redhat-actions/podman-installer@v1

      - name: Build image
        run: |
          podman run --rm \
            -v ${{ github.workspace }}:/workspace \
