name: Build Bazzite Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Podman
        uses: redhat-actions/podman-installer@v1

      - name: Build image
        run: |
          podman run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            quay.io/ublue-os/builder:latest build

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag and Push image
        run: |
          podman tag localhost/localhost/bazzite:latest ghcr.io/${{ github.repository_owner }}/bazzite:latest
          podman push ghcr.io/${{ github.repository_owner }}/bazzite:latest
